### ISSUE TITLE
Multi users and the private token field

### ISSUE THREAD

**Issue by leighshepperson** [jamesholcombe/dash-auth-external#16]
Hey, nice library!

So the session token gets set to a private field. This is an issue in a multi-user environment since users are effectively logged in using another user's token. It also means the same user is logged in cross browser or in incognito mode.

Since most of the code is already using session cookies, is there a reason why it can't be modified to just use that?

**Comment by jamesholcombe** [comment]
Thanks for the issue. 
Great points raised. I'll have a look at this.
