### ISSUE TITLE
'session' cookie is too large

### ISSUE THREAD

**Issue by Sclafus** [jamesholcombe/dash-auth-external#21]
Hey there, thanks for the library!
We are trying to use it, but we are facing an issue with the dimensions of the session cookie:
```python
/py39/lib/python3.9/site-packages/werkzeug/sansio/response.py:230: UserWarning:

The 'session' cookie is too large: the value was 4606 bytes but the header required 26 extra bytes. The final size was 4632 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
```
What we tried:
- `auth.server.config["SESSION_TYPE"] = "filesystem"`
- Using a smaller `_secret_key` parameter

Do you have any insight?
Thanks :D

**Comment by jamesholcombe** [comment]
This might be an oversight on my behalf with some recent changes. I'll have a look in the next few days and release a patch

**Comment by Sclafus** [comment]
Thanks for the fast reply!

**Comment by Sclafus** [comment]
False alarm. Apparently we were using an older version of the library (v0.3.0)
In version 1.0.1, the issue is not present anymore!
