### ISSUE TITLE
Add client-secret to post params when fetching token

### ISSUE THREAD

**Issue by raul-a-soriano-db** [jamesholcombe/dash-auth-external#23]
There are scenarios where it may be required to have client-secret as a form parameter in the "token_request" function

**Comment by jamesholcombe** [comment]
v1.1.0 should handle this use case. Thanks for the spot

**Comment by raul-a-soriano-db** [comment]
Thank you very much.

You can't imagine how much I appreciate it.

I was thinking in proposing you to implement it myself 

Thank you.
