### ISSUE TITLE
Protect page view

### ISSUE THREAD

**Issue by jpfcabral** [jamesholcombe/dash-auth-external#25]
It would be great if it were possible to protect the view of the pages.

For example, when we used links, the application would redirect directly to the login page

**Comment by jamesholcombe** [comment]
Not quite sure I follow, would you be able to expand on your example? And the desired behaviour/functionality?

**Comment by jpfcabral** [comment]
Sure. If we access any endpoint of our app, we need to check the authentication before show up the page content. 

At the moment we can verify the token only after show the page content, by callbacks.

The expected behavior follows:
- User isnt logged
- User type host by an endpoint. i.e: http://localhost:8050/myprofile
- User is redirected to auth endpoint to auth page

**Comment by jamesholcombe** [comment]
Okay I think I understand your point.

This library wasn't originally designed to provide actual user authentication for an app, but rather allow an app to access resources on a user's behalf. 

In my original use case, I was using another authentication provider, which locked down the entire domain.

I will have a think if/how to implement this, but if you need a solution asap, I suggest trying to configure the flask server before instantiating Dash. 

You may need to fork the repo, to ensure the routes that this library adds doesn't mess up your solution.



Hope that helps.

**Comment by jamesholcombe** [comment]
I'd be curious if you do implement a solution, and would be happy to incorporate into the library.
