### ISSUE TITLE
Multipage Dash app support

### ISSUE THREAD

**Issue by GitHunter0** [jamesholcombe/dash-auth-external#30]
First congratulations for the project, Dash is really lacking authorization packages.

Does `dash-auth-external` work for [Dash Multi-page app](https://dash.plotly.com/urls) paradigm?

**Comment by jamesholcombe** [comment]
yes and no. I see no reason why the lib would not work with a multi page app, however the library does protect page views and just allows access to a token on the server to fetch data from some 3rd party service. See #25 for details

**Comment by GitHunter0** [comment]
Thank you for the feedback @jamesholcombe . 
Would you be able to expand the scope of your module to comprise authentications with local/remote databases?
There is no current package implementing that... It would be a major contribution for Dash free users.

**Comment by jamesholcombe** [comment]
No worries. 
A couple of points. What do you mean when you say "comprise authentications with local/remote databases" ? 
I don't think that your problem is relevant to this library, but if you can expand on your use case with specifics I am happy to provide some guidance :)

**Comment by jamesholcombe** [comment]
Your dash app (actually a flask API) will be running on some server X, and your database will be running on some server Y. Your API will typically authenticate to the database using a connection string. This connection string is only visible to the server, and never the user/browser. You can use any python ORM for operations between your API, and the database. Not just libs specific to dash.  Hope that helps.

**Comment by GitHunter0** [comment]
Thank you @jamesholcombe , I appreciate the feedback, I will do some experiments and if I can't get it done, I will come back here.
