### ISSUE TITLE
Refresh Tokens - not working as expected even though Auth provider provides refresh_token

### ISSUE THREAD

**Issue by jagadish7s** [jamesholcombe/dash-auth-external#32]
After token expiry I do get below exception while calling get_token

@ Line #166 
`Exception: 'dict' object has no attribute 'refresh_token'`

![image](https://github.com/jamesholcombe/dash-auth-external/assets/165806466/28593763-3cc2-4f7c-8381-98f8f50005bc)

**Comment by jamesholcombe** [comment]
Thanks for the report. Sounds like a bug, I'll look into it

**Comment by jagadish7s** [comment]
When can I expect this fix.
